### ISSUE TITLE
[windows] System tray icon is not removed when application exits

### ISSUE THREAD

**Issue by ferenczy** [Yubico/yubioath-desktop#177] opened 2017-08-25 14:57 UTC
When I exit Authenticator (and process is really terminated), it doesn't remove the system tray icon and it doesn't disappear until I hover the cursor over it.

Version: 4.1.4

**Comment by dagheyman** [comment] 2017-08-28 11:08
Does this happen every time? Is it on Windows 7?

**Comment by Nesos-ita** [comment] 2017-09-07 14:22
yes, every time, on windows 7 (here)

**Comment by dagheyman** [comment] 2017-09-26 07:54
Reproduced on Windows 10 as well.

**Comment by emlun** [comment] 2017-11-17 16:53
Reproduced again in Win10, but this doesn't look to me like a bug in the yubioath-desktop app. Since the process exits immediately when you click Quit, and the icon then disappears as soon as you point at it again, I'm more inclined to call this a bug in Windows.

**Comment by ferenczy** [comment] 2017-11-21 17:59
@emlun I really don't know how it's supposed to work in Windows but I can imagine that this behavior is happening when you don't explicitly remove the icon before exiting the app.

**Comment by emlun** [comment] 2017-11-23 10:00
Ah yes, you are right. My thanks and apologies, this will be fixed in the next release.

**Comment by emlun** [comment] 2017-11-24 20:29
Fixed in 77fbaab

**Closed by emlun** 2017-11-24 20:29 UTC
Labels: bug
