### ISSUE TITLE
Small touch requirement bug

### ISSUE THREAD

**Issue by ElecM8** [Yubico/yubioath-desktop#282] opened 2018-04-13 14:31 UTC
- Yubico Authenticator version: 4.3.3 (Though bug is somewhat old)
- Operating system and version: ArchLinux (bug reproduced on Windows 7 x64 as well)
- YubiKey model and version: Yubikey 4 (No idea what version though...)
- Bug description summary: Touch requirement bug after pressing ESC when prompted to touch Yubikey, trying to generate new code will give out the previous, cancelled one.

Steps to reproduce
---

Have a few entries (at least two) that require touching the yubikey to display the OTP code.
Double-click on a credential, we'll call it Cred_A, Authenticator prompts you to touch the Yubikey.
Press ESC at that moment (Maybe you clicked the wrong credential, whatever) to remove the prompt.
Double-click on a second credential, we'll call it Cred_B, Authenticator prompts you to touch the Yubikey.
Touch the Yubikey to receive OTP code

Expected result
---
Authenticator gives me Cred_B's OTP code

Actual results
---
Authenticator gives me Cred_A's OTP code

Other info
---

While double clicking again on Cred_B and pressing the yubikey works fine after that bug, this bug will happen as many times as you've pressed ESC. The codes given will be in order of what you've tried to generate.

If you do Cred_A -> ESC -> Cred_B -> ESC -> Cred_C -> Touch, it will first give you Cred_A's OTP, touching again will give you Cred_B's OTP, and only on the third time will you get the proper code.
Bit of a messy report, sorry lol.

**Comment by dagheyman** [comment] 2018-04-18 09:56
Thanks for the report! I can reproduce the behaviour, I'll look into if we can do anything about it.

**Comment by dagheyman** [comment] 2019-09-25 08:27
This is a bit hard to do something about, since there is no way to cancel a call for a touch credential after it has been sent to the device. Even if we could ignore the first credential if a new touch credential was requested, the user would still have to touch the device twice. 

However, since version 5.0.0 there is not a modal dialog for the touch prompt, which I believe makes this less of a problem. Closing.

**Closed by dagheyman** 2019-09-25 08:27 UTC
Labels: bug
