### ISSUE TITLE
Fails when Yubikey NEO has all modes enabled

### ISSUE THREAD

**Issue by dharrigan** [Yubico/yubioath-desktop#15] opened 2014-10-29 10:35 UTC
Hi,

New Yubikey NEO with all modes enabled (-m86 (OTP/U2F/CCID composite device))

![yubikey](https://cloud.githubusercontent.com/assets/427150/4824139/1e39138a-5f57-11e4-81dd-26ec3b79df7c.png)

'''
python yubicoauthenticator/yubico_authenticator.py 
'NoneType' object has no attribute '_cmd_ok'
No smartcard reader found with YubiOath applet
'''

-=david=-

**Comment by ViViDboarder** [comment] 2015-01-06 17:59
I'm getting this too. When does it work? What mode do you have to disable?

**Comment by dharrigan** [comment] 2015-01-15 20:09
Hi,

I haven't revisited this since I created the initial report. Perhaps it's still broken? I've moved on from it worrying about it :-)

-=david=-

**Comment by drohm** [comment] 2015-02-04 23:10
I'm running LinuxMint 17.1 xfce 64-bit and I'm getting this error.  Was there a solution to this error?

**Comment by raabf** [comment] 2015-04-21 14:11
I think the U2F module is the problem. It still works on Windows. See #22 for a more detailed description of the issue.

**Comment by seelengut** [comment] 2015-05-01 20:05
Same issue happening on OSX (Mavericks) with a new NEO I just got. U2F is enabled by default in it.

**Comment by ViViDboarder** [comment] 2015-06-12 20:55
@dainnilsson

Any advice here? Seems like the project is far for abandoned despite being unusable for a number of people...

**Comment by drohm** [comment] 2015-06-12 21:13
I was able to get this working (LinuxMint 17.1 and Xubuntu 15.04) by doing the following:

* YubiKey Setup and Configuration:
	* Yubikey Authenticator:
		* Clone the git repository on Github:
			* git clone https://github.com/Yubico/yubioath-desktop.git
		* Open Software Manager, search for 'libccid' and install it.
		* Patch the info.plist:
			* sudo sh -c 'wget -q -O - https://raw.githubusercontent.com/Yubico/yubikey-neo-manager/master/resources/linux-fix-ccid-udev | python'
		* Install all dependency packages:
			* sudo apt-get install pcscd python-pyscard python-pbkdf2 python-pyside.qtgui
    
   	* Yubikey Desktop applications:
		* Add Yubico PPA to PPA sources:
			* Reference: https://launchpad.net/~yubico/+archive/ubuntu/stable?field.series_filter=trusty
			* In Update Manager
			* Edit...Software sources
			* Select PPAs button
			* Add 'ppa:yubico/stable'
				* Alternative way: sudo add-apt-repository ppa:yubico/stable
			* sudo apt-get update
			* sudo apt-get install ykneomgr
			* sudo apt-get install yubikey-neo-manager
			* sudo apt-get install yubikey-personalization
			* sudo apt-get install yubikey-personalization-gui
    
	* Google U2F (Chrome, etc...) [This isn't needed after patching info.plist from above]
		* References:
			* https://www.youtube.com/watch?v=nz6sYGQtP4I
			* https://www.yubico.com/faq/enable-u2f-linux/
			* https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules
		* Create file: /etc/udev/rules.d/70-u2f.rules
			* sudo nano /etc/udev/rules.d/70-u2f.rules
			* Paste in the content from 3rd link above and save.

This was all gathered from my post in the Yubico forums: http://forum.yubico.com/viewtopic.php?f=26&t=1727

Hope that helps.

**Comment by dainnilsson** [comment] 2015-06-15 08:15
@ViViDboarder Advice? Sure. I suggest you sit tight for a few more days. As I assume you were referring to, there's been a lot of activity with this project over the past month or so: I've taken over ownership of the project and have been re-writing it from scratch with the goal of improving the user experience as well as adding support for TOTP using the YubiKey standards slot based challenge response mode. This has yet to result in a new release, but is very close now. The latest release for this project, 0.1.1, is more than a year old, and all open issues are targetting that version. I'll be closing all open issues once the new release is out (2.0.0).

For this particular issue, it does sound like the problem is with your libccid configuration, and the instructions provided in this thread (or in the README or this project) should help you get past it. This will be required for the new version as well.

**Comment by ViViDboarder** [comment] 2015-06-15 16:20
Great! Thanks for the status update. I hope can understand my uncertainty
when I see commit activity with no communication after quite a while. I'm
glad that you're working towards a 2.0.

Does the package installer not automatically patch this? I figured it would
be one of the install steps. I'll run the script and see if that fixes it
and wait until the next release before opening new tickets.

**Comment by dainnilsson** [comment] 2015-06-16 13:00
The new version is out. @ViViDboarder what OS are you using? The installer for OS X should run the patch for you. You can verify by looking at the file: /usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist

If correctly patched it should contain entries for all combinations of modes for the YubiKey NEO, such as U2F+CCID, OTP+U2F+CCID, etc.

**Comment by drohm** [comment] 2015-06-16 15:05
@dainnilsson To install the newest version on linux (ubuntu), simply use the ppa?  Does it take a bit to get populated or something because I added the ppa but when I go to install yubioath-desktop its saying "Unable to locate package yubioath-desktop".

I added: ppa:yubico/stable

**Comment by dainnilsson** [comment] 2015-06-16 15:10
@drohm The PPA release juuuuuuust finished building, and will take a few minutes before it becomes available. It should be enough to just wait for a while. You can check on the status here: https://launchpad.net/~yubico/+archive/ubuntu/stable/+packages?batch=75&memo=75&start=75
Once the package has a green checkbox you should be good to go, just do an apt-get update first!

**Comment by drohm** [comment] 2015-06-16 15:25
@dainnilsson Excellent, just got it.  Well done on the new release, looks great and works very well.

**Comment by ViViDboarder** [comment] 2015-06-16 16:42
@dainnilsson awesome! Thanks! Just ran the installer on my Mac (10.10.3) and it still won't recognize my key.

I checked and I can find the following in `/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist`.

```
<string>Yubico Yubikey 4 OTP+U2F+CCID</string>
<string>Yubico Yubikey 4 U2F+CCID</string>
<string>Yubico Yubikey 4 OTP+CCID</string>
<string>Yubico Yubikey 4 CCID</string>
<string>Yubico Yubikey NEO OTP+U2F+CCID</string>
<string>Yubico Yubikey NEO U2F+CCID</string>
```

Thoughts?

**Comment by ViViDboarder** [comment] 2015-06-16 16:47
Decided to reboot my computer and that solved it! Looks great!

:+1: @dainnilsson

**Comment by raabf** [comment] 2015-06-17 01:53
Per default only those entries are in `/etc/libccid_Info.plist`:

```
<string>Yubico Yubikey NEO OTP+CCID</string>
<string>Yubico Yubikey NEO CCID</string>
```

Well this should be the reason why it stopped working after activating U2F.

`yubioath` (the gui) still show that I have to insert the yubikey NEO. But `yubioath-cli`and the old v0.1.1 gui are now working. Therefore this seems to be another not related bug  ....

**Comment by dainnilsson** [comment] 2015-06-17 07:41
@ViViDboarder Great, I'll make a note of that in the README!

@raabf Strange that it's working with yubioath-cli but not the GUI. Perhaps this is related to #26? As you say, since it's working with the CLI tool it doesn't sound like an issue with the libccid configuration.

**Comment by dainnilsson** [comment] 2015-06-18 08:05
@raabf Ok, so not related to #26. It seems very strange that it's working for the CLI tool but not the GUI. Does it work in any of the modes (pure CCID for example)?

**Comment by raabf** [comment] 2015-06-21 23:28
I do the following:

1. delete both slots (they was password protected) 
2. Only enable CCID -> yubioath gui works afterwards
3. enable all modes again -> yubioath gui works afterwards
4. set static password and challange respond to the slots (no password protection) -> yubioath gui works afterwards
5. set static password and challange respond to the slots (password protection). My yubikey neo is now in the same state as is was before step1 (my original configuration)  -> yubioath gui works afterwards

Actually it works. strange ... :confused:

**Comment by dainnilsson** [comment] 2015-06-22 07:41
Strange... But seeing that it works now I'll close this issue. Please open a new one if you have further issues.

**Closed by dainnilsson** 2015-06-22 07:41 UTC

**Comment by raabf** [comment] 2015-06-22 12:15
Yea do that :-) . Maybe I have more information, if it ever happens again.
