### ISSUE TITLE
Sporadic issue deleting credentials - "delete credential" popup does not appear and app locks up

### ISSUE THREAD

**Issue by jaffadog** [Yubico/yubioath-desktop#256] opened 2018-02-06 15:14 UTC
- Yubico Authenticator version: 4.3.2
- Operating system and version: Win 10
- YubiKey model and version: yubikey 4
- Bug description summary: Sporadic issue deleting credentials - "delete credential" popup does not appear and app locks up.

Steps to reproduce
---

After using the app for some period of time, try delete a credential:
- select credential
- right click > select delete
- no popup appears; you get a ding sound; app becomes unresponsive

Expected result
---

The "Delete Credential" confirmation popup window should appear.

Actual results
---

Sporadically, the "Delete Credential" confirmation popup window does not appear and the yubibo authenticator app becomes unresponsive and must be killed to recover.

Other info
---

[Anything else you would like to add?]

**Comment by emlun** [comment] 2018-02-06 15:16
Thanks for the report. What approximate order of magnitude (minutes, hours, days?) is "some period of time"?

**Comment by jaffadog** [comment] 2018-02-07 00:01
HI - I have not fully characterized this behavior. It's certainly with a couple days. I do "sleep" my laptop nightly and the YA app runs 24x7 in the tray. I am doing some testing - so frequently adding and deleting new OATH creds.

**Comment by emlun** [comment] 2018-02-07 14:02
Ok. I'm afraid a couple days isn't something we can reasonably attempt to reproduce, but it would be interesting to see some application logs. In practice our `--log-level` option isn't currently supported in the official Windows release, but the next release will add a `--log-file` option that'll enable it to work in Windows too. Can we get back to you on this when the next release is out?

**Comment by dagheyman** [comment] 2018-02-16 08:13
A new release (4.3.3) with better logging support is out. On windows you should be able to start Yubico Authenticator from the command line with `yubioath-desktop.exe --log-level DEBUG --log-file debug.log` to log debug output to a file.

**Comment by dagheyman** [comment] 2018-04-19 06:40
Closing due to lack of information.

**Closed by dagheyman** 2018-04-19 06:40 UTC
Labels: bug
