### ISSUE TITLE
🐞 Bug Linux - `yubioath-desktop` - breaks after `yubikey-manager` 5.0 update

### ISSUE THREAD

**Issue by Rikj000** [Yubico/yubioath-desktop#809] opened 2022-11-03 17:02 UTC
## Environment
| Software                        | Version                          |
| ------------------------------- | -------------------------------- |
| Yubico Authenticator            | 5.1.0                            |
| YubiKey Manager (ykman) version | 5.0.0                            |
| Kernel / Operating System       | 5.15.76-1-MANJARO                |
| YubiKey model                   | YubiKey 5 NFC                    |
| Bug description summary         | Authentication keys not detected |

## Steps to reproduce
- Install latest Manjaro KDE ([also reported on native Arch](https://bugs.archlinux.org/task/76325))
- Update all packages to the latest version
- Install the latest `yubioath-desktop` + `yubikey-manager` from the official repositories
- Enable the card-reader service with `sudo systemctl enable pcscd; sudo systemctl restart pcscd`
- Open the application with `yubioath-desktop --log-level DEBUG`

## Expected result
Authentication keys being detected

## Actual results
No authentication keys being detected, `ImportError` error thrown

### Fix suggestion
- [Arch Bugs - `yubioath-desktop` - breaks after `yubikey-manager` 5.0 update](https://bugs.archlinux.org/task/76325)
- [GitHub - `yubikey-manager` - commit - `connect_to_device` fully replaced by `list_all_devices`](https://github.com/Yubico/yubikey-manager/commit/87bc2e2a0a8e4285725155b3de3feb29942f183f)
- [GitHub - `yubioath-desktop` - current - `connect_to_device` still needs to be replaced with `list_all_devices`](https://github.com/Yubico/yubioath-desktop/blob/17aafed6f668614800dbd64c6dd51565a7f9b85a/py/yubikey.py)

### yubioath-desktop error
```log
ImportError: cannot import name 'connect_to_device' from ykman.device
Unhandled PyOtherSide error: Cannot import module: yubikey
```

### yubioath-desktop + ykman logs
<details>
  <summary markdown="block">
  Click to Expand/Collapse
  </summary>

```log
yubioath-desktop --version; ykman --version
===========================================
Yubico Authenticator 5.1.0
YubiKey Manager (ykman) version: 5.0.0

yubioath-desktop --log-level DEBUG
==================================
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
qrc:/qml/main.qml:353:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 4. Use 'sequences: [ <key> ]' to bind to all of them.
qrc:/qml/main.qml:297:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 9. Use 'sequences: [ <key> ]' to bind to all of them.
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 23, in <module>\n    from ykman.device import scan_devices, list_all_devices, connect_to_device, get_name, read_info\n\nImportError: cannot import name 'connect_to_device' from 'ykman.device' (/usr/lib/python3.10/site-packages/ykman/device.py)\n"
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in <module>
    from ykman.device import scan_devices, list_all_devices, connect_to_device, get_name, read_info

ImportError: cannot import name 'connect_to_device' from 'ykman.device' (/usr/lib/python3.10/site-packages/ykman/device.py)
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init_with_logging' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.is_win_non_admin' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'winNonAdmin' of undefined undefined
```

</details>

### pcscd + gpg logs

<details>
  <summary markdown="block">
  Click to Expand/Collapse
  </summary>

```log
sudo systemctl status pcscd
===========================
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
     Active: active (running) since Thu 2022-11-03 07:58:45 CET; 36min ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 20337 (pcscd)
      Tasks: 6 (limit: 154455)
     Memory: 1.4M
        CPU: 152ms
     CGroup: /system.slice/pcscd.service
             └─20337 /usr/bin/pcscd --foreground --auto-exit

Nov 03 07:58:45 Linux-Workstation systemd[1]: Started PC/SC Smart Card Daemon.
Nov 03 07:59:16 Linux-Workstation pcscd[20337]: 00000000 ccid_usb.c:886:WriteUSB() write failed (1/18): LIBUSB_ERROR_NO_DEVICE
Nov 03 07:59:16 Linux-Workstation pcscd[20337]: 00000013 ccid_usb.c:1488:InterruptRead() libusb_submit_transfer failed: LIBUSB_ERROR_NO_DEVICE

gpg --card-status
=================
Reader ...........: Yubico YubiKey OTP FIDO CCID 00 00
Application ID ...: D2760001240103040006190211350000
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....: 19021135
Name of cardholder: [not set]
Language prefs ...: [not set]
Salutation .......: 
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Key attributes ...: rsa2048 rsa2048 rsa2048
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 0 3
Signature counter : 0
KDF setting ......: off
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]
```

</details>

**Comment by emlun** [comment] 2022-11-03 17:12
This looks like a duplicate of Yubico/yubikey-manager#523. Please continue any further discussion there.

**Closed by emlun** 2022-11-03 17:12 UTC
