### ISSUE TITLE
Notification Icon oversized

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#66] opened 2016-01-23 23:30 UTC
I reported this issue back when I was using Xubuntu 15.10 Beta 2 (https://github.com/Yubico/yubioath-desktop/issues/53) and it seemed to go away with the official released version of 15.10, but it seems to be back.

![sshot_yubioath_notification_icon_oversized](https://cloud.githubusercontent.com/assets/184959/12533466/f778779e-c1fd-11e5-920d-535921303f7d.png)

I've tried uninstalling (apt-get remove and apt-get --purge) with reboot and it still shows the oversized icon in the notification area after a fresh install.  I can't seem to figure this one out.  Could this possibly be a theme issue where it's cached somewhere?

System info:
![sshot_sysinfo](https://cloud.githubusercontent.com/assets/184959/12533495/cffd6002-c1fe-11e5-8304-8390771701db.png)

**Comment by dainnilsson** [comment] 2016-03-02 15:25
It does sound like something might be cached somewhere that isn't getting purged. I haven't been able to reproduce this myself, and I've run it on multiple versions of XUbuntu, including 15.10. Unfortunately I have no idea as to what is causing it in your case.

**Comment by drohm** [comment] 2016-06-09 02:01
I'm still experiencing this problem, even on a completely different system (LinuxMint 17.3).

**Comment by dagheyman** [comment] 2017-03-20 12:09
Is this still the case with the new version (4.0.0) ?
https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by drohm** [comment] 2017-03-20 16:26
I will test this out and let you know.  I'm currently having a problem with the latest version that was just released (4.0.0).  It upgraded successfully, but it won't launch.  I'll create a new ticket.

**Comment by dagheyman** [comment] 2017-03-21 07:42
I'm closing this since the systray icon was dropped in the latest version. See #125

**Closed by dagheyman** 2017-03-21 07:42 UTC
