### ISSUE TITLE
Improved Keyboard User Experience (Handling Focus)

### ISSUE THREAD

**Issue by ilya40umov** [Yubico/yubioath-desktop#144] opened 2017-03-29 13:21 UTC
Version: 4.0.1
OS: Linux Mint 18.1 with Cinnamon

Consider the following use case:
1. User opens Authenticator app
2. Uses Ctrl+F shortcut to search for an entry
3. At this point Authenticator highlights the first found entry in the list (as if it were selected), however if I press Ctrl+C it does not copy the generated code (which is the most annoying problem)
4. Pressing Up/Down arrows at this point also does not lead to moving between oath entries (sometimes it opens File menu and sometimes does nothing). 

The only thing that helps is using mouse pointer to click in the list to select the entry and then pressing Ctrl+C.

**Comment by dagheyman** [comment] 2017-03-29 13:54
> The only thing that helps is using mouse pointer to click in the list to select the entry and then pressing Ctrl+C.

You could also put the focus on the credentials again with the <kbd>tab</kbd> key instead of the mouse. 
But yes, maybe Ctrl + C (or maybe Enter?) should copy the selected credential when the search bar has focus.

**Comment by ilya40umov** [comment] 2017-03-29 13:59
> You could also put the focus on the credentials again with the tab key instead of the mouse.
Yep. Tab key works as well. The only problem is that I can not reliably use Tab key right now, because when the list receives the focus it does not change in any way.

**Comment by rmenessec** [comment] 2017-06-07 18:54
Commenting on this issue because I think it's related, although I'm reporting from Windows. (But I've had the same problem on Linux.)

Issue: After selecting an OTP entry and copying to clipboard, Authenticator works as expected. **However,** if copying a second time—at least with Ctrl+C—the first OTP code is merely copied to clipboard again, instead of whatever new code has been generated since the first.

This is "fixable" by de-selecting the OTP entry and re-selecting it. However, this shouldn't be a requirement. It should behave as the original app did: sanely, by copying the new code from the still-selected OTP entry.

I would tend to consider this more clearly a bug / misfeature than an enhancement; I can create a separate issue if you prefer, @dagheyman .

**Comment by dagheyman** [comment] 2017-06-08 07:15
@rmenessec nice catch, definitely a bug. I managed to reproduce it. I'll open a separate issue.

**Comment by dagheyman** [comment] 2017-08-03 12:23
Closing this since a number of small tweaks is implemented in version 4.1.3:
- Pressing Enter when search has focus generates/copies the code from the selected credential.
I decided to not overwrite "Ctrl + C" behaviour inside the textfield.
- Pressing ESC key clears search field, deselects the credential and removes focus from search
- Clicking outside search removes focus from search.

**Closed by dagheyman** 2017-08-03 12:23 UTC
Labels: enhancement
