### ISSUE TITLE
[windows] Right click menu appears on wrong monitor

### ISSUE THREAD

**Issue by darkain** [Yubico/yubioath-desktop#215] opened 2017-12-04 20:48 UTC
Under Windows with multi-monitor support, the right-click menu doesn't appear at the mouse cursor's location, instead it appears on another monitor.

1) Set up multiple monitors.
2) Add a monitor to the left of the primary, giving it a negative X axis (alternatively, one above the primary, for a negative Y axis)
3) Move the window to this other monitor.
4) Right-click within the window to bring up the context menu
5) Menu appears on primary monitor, instead of monitor where the window is currently located

**Comment by emlun** [comment] 2017-12-05 11:42
Hah, interesting bug. Thanks for erporting, we'll take a look at it!

**Comment by darkain** [comment] 2017-12-05 18:18
Yeah! In the earlier days of multi-monitor support in Windows, this was a very common bug to see in countless applications. They just all assume that a negative coordinate is impossible (or they use unsigned integers for coordinates). Its been a while since I've seen this is a desktop application! Pretty easy to fix though usually.

**Comment by emlun** [comment] 2017-12-08 16:14
Hm, I'm actually not able to reproduce this with Yubico Authenticator 4.2.0 in a Windows 10 VM. Did I understand correctly that this is what you did?

The context menu does appear on the rightmost (primary) display if the Yubico Authenticator window is straddling the border in such a way that the window peeks out less to the left than the width of the context menu, but it doesn't seem like that corner case was what you meant.

![deepinscreenshot_select-area_20171208170740](https://user-images.githubusercontent.com/1367758/33774118-805ecd12-dc3a-11e7-872b-42706de6bcec.png)

**Comment by emlun** [comment] 2017-12-12 12:07
Closing this for now, please reopen when you respond!

**Closed by emlun** 2017-12-12 12:07 UTC
Labels: bug
