### ISSUE TITLE
[Mac] UI updates only after tabbing out and back in

### ISSUE THREAD

**Issue by marbuser** [Yubico/yubioath-desktop#332] opened 2019-02-21 06:20 UTC
- Yubico Authenticator version: 4.3.5
- Operating system and version: macOS 10.14.3
- YubiKey model and version: YubiKey 5 NFC
- Bug description summary: 
The mac authenticator app is incredibly buggy. The UI only updates if you tab out and back in. For example, if I open the "new credentials" pane and type something, nothing will show up, but if I tab out and back into the app, it instantly appears. This is incredibly annoying.

This also happens with detecting the YubiKey. For example, if you plug in your yubikey, it will say "No YubiKey Detected" and if you tab out and back in it will register. Same goes for the codes regenerating and such. It's incredibly annoying.

I was also under the impression that the experience would be a little smoother than it currently is. For example, say I login to some service, I would expect that I could just touch my yubikey, and it auto copies the correct code. But no, you have to manually open the yubikey authenticator app, manually copy the code, and then paste it into the service.

I don't know if what I said initially is the intended functionality, but it doesn't work.

Steps to reproduce
1. Buy a Yubikey
2. Download the app
3. ??? 

Expected result
App should work smoothly without idiotic tabbing out and in, and the app should auto copy the relevant OTP based on what you have open when you touch the key.
E.G if I have a OTP registered with Twitter, it would make sense to copy the OTP if my browser is open on the twitter domain.

**Comment by emlun** [comment] 2019-02-21 13:35
Thanks for the report. First off:

>the app should auto copy the relevant OTP based on what you have open when you touch the key.

This would require some kind of inter-process communication between the Authenticator app and each individual browser, which we have no plans to implement. It's also not possible to have the YubiKey generate a TOTP just by touching it, because the YubiKey needs to receive the current time from the host computer as a parameter in order to generate the TOTP.

WebAuthn and U2F do work something like that - letting you simply touch the YubiKey when prompted with no separate authenticator app required - but those technologies are very different from TOTP.

---

As for the other part, this is definitely not intended behaviour:

>The UI only updates if you tab out and back in. For example, if I open the "new credentials" pane and type something, nothing will show up, but if I tab out and back into the app, it instantly appears. [...]
>This also happens with detecting the YubiKey. For example, if you plug in your yubikey, it will say "No YubiKey Detected" and if you tab out and back in it will register. Same goes for the codes regenerating and such. [...]

- When you say 'if I open the "new credentials" pane and type something, nothing will show up', do you mean the text input fields to not respond at all to input unless you tab out and back in?
- Could you try running Yubico Authenticator with the `--log-level DEBUG` option and post the output here?

**Comment by marbuser** [comment] 2019-02-21 14:15
@emlun Ah ok, well I guess I can live with that. If we can get the apps to work then that would be perfect.

This is an example of what I mean regarding the nothing will show up.
https://i.imgur.com/2y7yQhh.mp4

Also this is a general theme throughout the whole application, when copying OTP and such it does this as well.

I also have a bit of an update on this, it isn't just tabbing out, it's when the window is out of view completely. If I tab out and the window is still visible and then tab back in, it doesn't work. But if I tab out and the window goes behind another window like Chrome or finder, and then tab back in, the input is filled.

Also somewhat related but maybe not the right place, I also get this with the Manager;
![image](https://user-images.githubusercontent.com/34422459/53174778-90a60500-3625-11e9-849a-517e4e375a78.png)

Multiple people I know have no issues with the software, so I'm thinking perhaps I'm missing a dependency or something is interfering that I already have installed.

Log requested: (Don't think there is any sensitive info in there)
```
2019-02-21T22:12:22+0800 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 2.0.0-dev
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x4, self.mode.transports: 0x7
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:86] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x10f870be0>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:198] Read config from device...
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040008a000000527471117'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'001d000000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:200] Success!
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:288] Identified YubiKey 5
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040007a0000005272101'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.__del__:269] Destroy <ykman.driver_ccid.CCIDDriver object at 0x10f870be0>
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x10f870be0>
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x4, self.mode.transports: 0x7
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:86] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x10f870b38>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:198] Read config from device...
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040008a000000527471117'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'001d000000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:200] Success!
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:288] Identified YubiKey 5
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040007a0000005272101'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.__del__:269] Destroy <ykman.driver_ccid.CCIDDriver object at 0x10f870b38>
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x10f870b38>
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x4, self.mode.transports: 0x7
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2019-02-21T22:12:22+0800 DEBUG [ykman.descriptor.open_device:86] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x10de3a2e8>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:198] Read config from device...
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040008a000000527471117'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'001d000000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:200] Success!
2019-02-21T22:12:22+0800 DEBUG [ykman.device.__init__:288] Identified YubiKey 5
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040007a0000005272101'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a400010a7408000000000314c1a8'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'711a3150617373776f72643a6d792e3170617373776f72642e636f6d7c01069000'
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.__del__:269] Destroy <ykman.driver_ccid.CCIDDriver object at 0x10de3a2e8>
2019-02-21T22:12:22+0800 DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x10de3a2e8>
```

**Comment by marbuser** [comment] 2019-02-22 12:30
Any updates on why this might be happening?

**Comment by marbuser** [comment] 2019-03-01 04:44
Any further updates? :/

**Comment by dagheyman** [comment] 2019-03-01 07:27
Sorry, I have not had time to look into this. My guess is something is wrong with the graphics/OpenGL-drivers in some way. Do you have any third-party graphics/video related software installed? I can't reproduce this on my macbook with macOS Mojave.

**Comment by marbuser** [comment] 2019-03-01 18:35
@dagheyman no worries. 
Not that I’m aware no. Could you perhaps give some examples so I can try searching my Mac for these drivers or software?

Because I definitely haven’t installed anything like that intentionally.

**Comment by marbuser** [comment] 2019-03-06 15:54
@dagheyman Updated. Just tested this on another Mac that is basically fresh install and same issues. Can try on another one if needed but I expect the same result probably.

**Comment by dagheyman** [comment] 2019-03-07 07:40
Very weird, we have not seen this on the macs we have tested on. Could you try starting the application from a terminal and see if it says anything interesting?

Something like this:
`$ /Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop`

**Comment by marbuser** [comment] 2019-03-08 13:09
@dagheyman 

Nope nothing. 

Here is an output using the debug log though.
```
/Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop --log-level DEBUG
2019-03-08T21:07:10+0800 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 0.7.0
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x4, self.mode.transports: 0x7
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x111c88048>, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:196] Read config from device...
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040008a000000527471117'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'001d000000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:198] Success!
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040007a0000005272101'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.__del__:213] Destroy <ykman.driver_ccid.CCIDDriver object at 0x111c88048>
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.close:209] Close <ykman.driver_ccid.CCIDDriver object at 0x111c88048>
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x4, self.mode.transports: 0x7
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:196] Read config from device...
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040008a000000527471117'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'001d000000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:198] Success!
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040007a0000005272101'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.__del__:213] Destroy <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.close:209] Close <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x4, self.mode.transports: 0x7
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2019-03-08T21:07:27+0800 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:196] Read config from device...
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040008a000000527471117'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'001d000000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-03-08T21:07:27+0800 DEBUG [ykman.device.__init__:198] Success!
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040007a0000005272101'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a400010a740800000000031569e6'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'711a3150617373776f72643a6d792e3170617373776f72642e636f6d7c01069000'
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.__del__:213] Destroy <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>
2019-03-08T21:07:27+0800 DEBUG [ykman.driver_ccid.close:209] Close <ykman.driver_ccid.CCIDDriver object at 0x111c880f0>
2019-03-08T21:07:37+0800 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x4, self.mode.transports: 0x7
2019-03-08T21:07:37+0800 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:37+0800 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2019-03-08T21:07:37+0800 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x1119d7198>, pid: PID.YK4_OTP_FIDO_CCID
2019-03-08T21:07:37+0800 DEBUG [ykman.device.__init__:196] Read config from device...
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040008a000000527471117'
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'001d000000'
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'2b0102023f0302023f02040092988904010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-03-08T21:07:37+0800 DEBUG [ykman.device.__init__:198] Success!
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a4040007a0000005272101'
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'79030501027108caf7271d2f6780cc9000'
2019-03-08T21:07:37+0800 DEBUG [ykman.driver_ccid.send_apdu:168] SEND: b'00a2000026711a3150617373776f72643a6d792e3170617373776f72642e636f6d740800000000031569e7'
2019-03-08T21:07:38+0800 DEBUG [ykman.driver_ccid.send_apdu:170] RECV: b'75150621d33af964dd339e1d9bf3241a6789bbcd164d379000'
2019-03-08T21:07:38+0800 DEBUG [ykman.driver_ccid.__del__:213] Destroy <ykman.driver_ccid.CCIDDriver object at 0x1119d7198>
2019-03-08T21:07:38+0800 DEBUG [ykman.driver_ccid.close:209] Close <ykman.driver_ccid.CCIDDriver object at 0x1119d7198>
```

I should mention that my problem with the manager was resolved. Just redownloaded it and it started showing up instead of being blank.
Tried downloading the latest version of the authenticator as well but same issue is happening.

**Comment by marbuser** [comment] 2019-03-10 01:15
@dagheyman I believe I have narrowed down the problem, but I'm still unsure as to what it is.

I've tested on 3 of the "new" MacBook Pro, 2017 and 2x 2018.
The issue persists on all of them, even with Fresh macOS install.

However, if I use it on a 2013 iMac, it works perfectly.

This leads me to believe that something was added to these new MacBooks whether that be Hardware or software related, and is causing these issues.

Perhaps you can look into it more.

**Comment by dagheyman** [comment] 2019-03-12 09:34
Thanks for the additional investigations. These new macbooks, are they all running macOS Mojave? We tried it here on a 2017 macbook as well, and couldn't reproduce the issue unfortunately. You could also try filing a ticket with [Yubico Support](https://support.yubico.com/support/tickets/new) to see if they have any ideas.

**Comment by marbuser** [comment] 2019-03-12 12:25
> Thanks for the additional investigations. These new macbooks, are they all running macOS Mojave? We tried it here on a 2017 macbook as well, and couldn't reproduce the issue unfortunately. You could also try filing a ticket with [Yubico Support](https://support.yubico.com/support/tickets/new) to see if they have any ideas.

Yep. All the devices I was testing on were running the latest macOS.
I will try contacting Yubico support, although I'm not hopeful, especially if you aren't sure what it is and you are the dev of the app. :/

**Comment by marbuser** [comment] 2019-04-11 16:45
@dagheyman I've managed to fix this. Turns out it was to do with OpenGL. Apparently OpenGL isn't installed on new Mac's anymore by default since they released their new Metal 2.

If anyone else has this issue, they can fix it by doing these commands in Terminal with brew installed;
```
brew install glfw3
brew install glew
```

Perhaps you could fix this in a future update by making the installer auto-install OpenGL? Or absolute minimum, add these commands to a wiki/faq page so people know how to fix it. :)

**Comment by dagheyman** [comment] 2019-09-24 06:54
Closing, I don't think manually installing OpenGL should be needed, but feel free open additional issues if needed. Note that version 5.0.0 moved to a newer UI framework (Quick Controls 2), the same one used in YubiKey Manager.

**Closed by dagheyman** 2019-09-24 06:54 UTC
