### ISSUE TITLE
No Yubikey detected after upgrading to 5.0.1

### ISSUE THREAD

**Issue by gbaptista** [Yubico/yubioath-desktop#498] opened 2019-12-11 12:44 UTC
- Yubico Authenticator version: 5.0.1
- Operating system and version: 4.19.88-1-MANJARO 64-bit (Qt 5.13.2)
- YubiKey model and version: YubiKey 5C
- Bug description summary: Yubioauth is stucked at "No Yubikey detected." It works with yubikey-manager 5.0.0.

Steps to reproduce
---

Install `yubioath-desktop` version `5.0.1`. Try to use it. The app displays `No Yubikey detected`.

Expected result
---

Recognize the Yubikey.

Actual results
---

"No Yubikey detected"

Other info
---

Logs:
```
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```

Workaround: Rollback to 5.0.0 and everything works again:
```bash
yay -S downgrade
DOWNGRADE_FROM_ALA=1 downgrade yubioath-desktop
```

Choose: `yubioath-desktop    5.0.0  4  x86_64`

**Comment by emlun** [comment] 2019-12-11 12:51
Thanks for the report! What version of the Python package `ykman` (often distributed as a packaged named `python3-yubikey-manager` or some such) do you have installed?

**Comment by gbaptista** [comment] 2019-12-11 12:54
`ykman --version`

```
YubiKey Manager (ykman) version: 3.1.0
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```

**Comment by emlun** [comment] 2019-12-11 15:07
Great, thanks! We'll have a look at it.

**Comment by emlun** [comment] 2019-12-12 15:53
I'm not able to reproduce this. Does it still fail if you install 5.0.1 again? Could you post the output from running the application with the `--log-level DEBUG` option?

**Comment by gbaptista** [comment] 2019-12-12 16:52
Sure:

`yubioath-desktop --log-level DEBUG`

```
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 27, in <module>\n    signal.signal(signal.SIGINT, signal.SIG_DFL)\n\n  File \"/usr/lib/python3.8/signal.py\", line 47, in signal\n    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))\n\nValueError: signal only works in main thread\n"
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 27, in <module>
    signal.signal(signal.SIGINT, signal.SIG_DFL)

  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

ValueError: signal only works in main thread
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init_with_logging' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```

**Comment by zsteinmetz** [comment] 2019-12-13 10:03
Got the same problem with the YubiKey 5 NFC on current Manjaro. Interestingly, the YubiKey is detected via YubiKey Manager but not with the Authenticator.

**Comment by fdennis** [comment] 2019-12-13 10:32
Hey guys,
This sounds like a duplicate of #491 

Have you tried the [AppImage](https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.1-linux.AppImage)?

**Comment by zsteinmetz** [comment] 2019-12-13 10:37
> Hey guys,
> This sounds like a duplicate of #491
> 
> Have you tried the [AppImage](https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.1-linux.AppImage)? Just want to check if that works instead.

You're right. AppImage works like a charm.

**Comment by fdennis** [comment] 2019-12-13 10:40
Great! I will refer to @emlun [comment ](https://github.com/Yubico/yubioath-desktop/issues/491#issuecomment-558586724 )in that issue regarding workarounds right now. A fix has been implemented and will be in the next release.

**Comment by FFY00** [comment] 2019-12-16 00:12
@fdennis can you tell me which commit fixed this? I want to backport it in the arch package.

**Comment by emlun** [comment] 2019-12-16 10:17
@FFY00 Commits 99be0c8f91e50f8777ab77818682951e3d162135, 729339d2be10e597c4eac06ebe4cd683b55c2ff7, 2066904b3c58aeaa8ee5000f6698a7e70c76fd93 in PR #493

**Closed by emlun** 2019-12-16 10:17 UTC

**Comment by FFY00** [comment] 2019-12-16 10:20
Thanks! Would it be possible to add some really simple tests to just make sure the API is there? No need to communicate with a real device. This way we could prevent this from happening again.

**Comment by emlun** [comment] 2019-12-16 11:34
Well, since we're now depending on the C++ API for signals, the app should no longer compile if that fails. Or did you mean something else?
