### ISSUE TITLE
Scan QR Code does not work on Gnome

### ISSUE THREAD

**Issue by arianvp** [Yubico/yubioath-desktop#235] opened 2018-01-15 12:16 UTC
- Yubico Authenticator version:  4.3.2
- Operating system and version: Ubuntu 16.04
- YubiKey model and version:  Yubikey 4.3.7
- Bug description summary: QR code scan does not work

Steps to reproduce
---

Install gnome on ubuntu 16.04. Or on Arch Linux. Install the authenticator App

Both XOrg and Wayland doesn't scan QR codes from screen

Expected result
---

I scan scan QR codes from the screen

Actual results
---

QR Code was not found

**Comment by emlun** [comment] 2018-01-16 11:58
Thanks for reporting! I'm not able to reproduce this in Arch Linux. Are you using multiple monitors?

**Comment by emlun** [comment] 2018-01-16 13:04
Ok, because I've seen this behaviour when the QR code is on one monitor and the Yubico Authenticator window is on another. Have you tried placing them on the same monitor before scanning?

**Comment by emlun** [comment] 2018-01-16 13:59
I've confirmed that the QR code scanner only captures QR codes on the primary monitor, this will be fixed in the next release. Thanks for reporting!

**Comment by emlun** [comment] 2018-01-22 16:18
This should be fixed in #239, let us know if you still have this problem after upgrading to (the not yet released) next release.

**Closed by emlun** 2018-01-22 16:18 UTC
Labels: bug

**Comment by unchainedio** [comment] 2020-08-03 05:21
i am getting this error on Manjaro/arch running i3 window manager.  I am unable to scan the qr code in another tiled window next to the yubico authenticator.  Is there a way to get this to work?
