### ISSUE TITLE
Yubikey Authenticator does not see YubiKey

### ISSUE THREAD

**Issue by charona** [Yubico/yubioath-desktop#704] opened 2021-05-07 05:37 UTC
After a Mac crash and reboot, Authenticator does not see my YubiKey(s) anymore.

The YubiKeys work, and I can use them to log in to sites without Authenticator, but Authenticator does not see them.
YubiKey Manager doesn't see them either.

Keys affected: 5 NFC, 5 Nano
MacOS Catalina 10.15.7
Authenticator 5.0.5

Super annyoing, as I need both keys to log in to lots of sites on a daily basis.

Any clues as to what's going on here?

**Comment by fdennis** [comment] 2021-05-07 06:01
Could you try running with the debug flag via the terminal? `./yubioath-desktop --log-level DEBUG`

**Comment by charona** [comment] 2021-05-07 06:23
Thanks. Where exactly do I find that binary? Can't find it in the app Contents/

**Comment by fdennis** [comment] 2021-05-07 06:27
Should be here `/Applications/Yubico Authenticator.app/Contents/MacOS`

**Comment by charona** [comment] 2021-05-07 07:50
Thanks. Resulted in this. While it was running I took out my 5NFC and plugged it back in again, which resulted in the second set of debug lines:

./yubioath-desktop --log-level DEBUG
qt.qpa.fonts: Populating font family aliases took 432 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
qrc:/qml/main.qml:63:13: QML StyledToolBar (parent or ancestor of Material): Binding loop detected for property "foreground"
2021-05-07T09:48:33+0200 INFO [ykman.logging_setup.setup:74] Initialized logging for level: DEBUG
2021-05-07T09:48:33+0200 INFO [ykman.logging_setup.setup:75] Running ykman version: 4.0.2
2021-05-07T09:48:33+0200 DEBUG [ykman.logging_setup.log_sys_info:47] Python: 3.9.2 (default, Apr 14 2021, 15:32:12) 
[Clang 12.0.0 (clang-1200.0.32.29)]
2021-05-07T09:48:33+0200 DEBUG [ykman.logging_setup.log_sys_info:48] Platform: darwin
2021-05-07T09:48:33+0200 DEBUG [ykman.logging_setup.log_sys_info:54] Running as admin: False
2021-05-07T09:48:33+0200 ERROR [ykman.device.list_all_devices:146] Failed opening device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/device.py", line 140, in list_all_devices
    with dev.open_connection(connection_type) as conn:
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/base.py", line 50, in open_connection
    return self._connection_cls(self.path)
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/macos.py", line 185, in __init__
    raise OSError(f"Failed to open device for communication: {result}")
OSError: Failed to open device for communication: -536870206
2021-05-07T09:48:41+0200 ERROR [ykman.device.list_all_devices:146] Failed opening device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/device.py", line 140, in list_all_devices
    with dev.open_connection(connection_type) as conn:
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/base.py", line 50, in open_connection
    return self._connection_cls(self.path)
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/macos.py", line 185, in __init__
    raise OSError(f"Failed to open device for communication: {result}")
OSError: Failed to open device for communication: -536870206

**Comment by fdennis** [comment] 2021-05-07 08:21
Thank you.
Do you have ykman cli installed? It can be installed through homebrew but it also comes bundled with YubiKey Manager GUI. If you have YubiKey Manager GUI installed you can find ykman cli in `/Applications/YubiKey Manager.app/Contents/MacOS/ykman`
Could you run the following command `./ykman --diagnose`?

**Comment by charona** [comment] 2021-05-07 09:43
I have Yubikey Manager installed (v 1.2.1).

`
./ykman --diagnose
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 367, in main
    cli(obj={})

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 760, in main
    _verify_python3_env()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/_unicodefun.py", line 126, in _verify_python3_env
    raise RuntimeError(

RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
`

**Comment by dainnilsson** [comment] 2021-05-07 09:50
Hmm. That error indicates that your Locale may be incorrectly configured. I've seen this happen on MacOS when running the command over SSH (where the SSH client sets the locale to an unsupported one). If you explicitly set a locale and run the command it should give us the correct output:

`LANG="en_US.UTF-8" ./ykman --diagnose`

**Comment by charona** [comment] 2021-05-07 11:26
Thanks. Results in:

```
LANG="en_US.UTF-8" ./ykman --diagnose
ykman: 4.0.1
Python: 3.9.2 (default, Mar 30 2021, 08:18:21) 
[Clang 12.0.0 (clang-1200.0.32.29)]
Platform: darwin
Running as admin: False

Detected PC/SC readers:

Detected YubiKeys over PC/SC:

Detected YubiKeys over HID OTP:
	OtpYubiKeyDevice(pid=0407, fingerprint='4295012784')
	OTP connection failure: Failed to open device for communication: -536870201


Detected YubiKeys over HID FIDO:
	CtapYubiKeyDevice(pid=0407, fingerprint='4295012790')
CTAP device version: 5.1.2
CTAPHID protocol version: 2
Capabilities: 5
	DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=10163582, version=Version(major=5, minor=1, patch=2), form_factor=<FORM_FACTOR.USB_A_KEYCHAIN: 1>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, is_locked=False, is_fips=False)
	RawInfo: 2b0102023f0302023f0204009b157e04010105030501020602000007010f0801000d02023b0e02023b0a0100
	Ctap2Info: {<VERSIONS: 0x01>: ['U2F_V2', 'FIDO_2_0'], <EXTENSIONS: 0x02>: ['hmac-secret'], <AAGUID: 0x03>: b'\xfa+\x99\xdc\x9e9BW\x8f\x92J0\xd2<A\x18', <OPTIONS: 0x04>: {'rk': True, 'up': True, 'plat': False, 'clientPin': False}, <MAX_MSG_SIZE: 0x05>: 1200, <PIN_UV_PROTOCOLS: 0x06>: [1]}
PIN: Not configured

End of diagnostics
```

**Comment by charona** [comment] 2021-05-08 13:07
Thanks for your help so far guys, but what am I to do in the meantime? Throw away the 3 YubiKeys I bought? Might as well ditch them if I can't use them. Not trying to be a pain here, but I had hoped that Yubico would make sure to solve this issue.

PS I'm using a Mac Pro 2019 in case that info helps.

**Comment by dainnilsson** [comment] 2021-05-11 08:01
I haven't been able to find out much, though I did find another useful command to test smartcard communication, which is `pcsctest`. Based on what we've already seen I suspect it won't be able to detect the smartcard interface, so it likely won't give you any new information.

I think we can conclude that the problem is unrelated to Yubico Authenticator: Your OS seems to be unable to detect a smartcard reader, for whatever reason, and that needs to be fixed before Yubico Authenticator can work. I don't have much MacOS knowledge to help you, you'll probably get more help by opening a support ticket either with Yubico Support or Apple Support.

Personally I would probably try things like creating a new user account and booting into that to see if that makes a difference, or even re-installing MacOS as a last resort. Sorry I can't help you more than that.

For reference in case it's useful, here's the output of running `pcsctest`:

```% pcsctest

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: Yubico YubiKey OTP+FIDO+CCID
Enter the reader number          : 1
Waiting for card insertion
                                 : Command successful.
Testing SCardConnect             : Command successful.
Testing SCardStatus              : Command successful.
Current Reader Name              : Yubico YubiKey OTP+FIDO+CCID
Current Reader State             : 0x54
Current Reader Protocol          : 0x1
Current Reader ATR Size          : 23 (0x17)
Current Reader ATR Value         : 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
Testing SCardDisconnect          : Command successful.
Testing SCardReleaseContext      : Command successful.
Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: Yubico YubiKey OTP+FIDO+CCID
Enter the reader number          : 1
Waiting for card insertion
                                 : Command successful.
Testing SCardConnect             : Command successful.
Testing SCardStatus              : Command successful.
Current Reader Name              : Yubico YubiKey OTP+FIDO+CCID
Current Reader State             : 0x54
Current Reader Protocol          : 0x1
Current Reader ATR Size          : 23 (0x17)
Current Reader ATR Value         : 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
Testing SCardDisconnect          : Command successful.
Testing SCardReleaseContext      : Command successful.

PC/SC Test Completed Successfully !```

**Comment by charona** [comment] 2021-05-11 18:12
Thanks man. Silly me was assuming I was talking to people from Yubico support, sorry :)

All I get with that command is this:

```
pcsctest

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange 
Please insert a working reader   :

```
Next stop Yubico support. Thanks again guys!

**Comment by fdennis** [comment] 2021-05-12 09:01
Closing this since it is not an issue with Yubico Authenticator.

**Closed by fdennis** 2021-05-12 09:01 UTC

**Comment by canadiannomad** [comment] 2022-02-20 18:44
I'm running into this identical problem (nearly identical logs, and output to the same test commands) ... @charona, if you do find a solution, please post it!
