### ISSUE TITLE
Build fails with pkg_resources.DistributionNotFound: The 'yubioath-desktop' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by philippsandhaus** [Yubico/yubioath-desktop#60] opened 2015-12-08 15:21 UTC
I get this strange error when trying to build an excecutable on Mac OS X

```
MacBook-Pro-2:yubioath-desktop-yubioath-desktop-2.3.0 sandhaus$ python setup.py executable
running executable
76 INFO: PyInstaller: 3.0
76 INFO: Python: 2.7.11
92 INFO: Platform: Darwin-15.0.0-x86_64-i386-64bit
93 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

    VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/local/opt/python/bin/python2.7

1110 INFO: UPX is not available.
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'Topic :: Utilities'
  File "/Users/sandhaus/Downloads/yubioath-desktop-yubioath-desktop-2.3.0/yubioath/yubicommon/setup/__init__.py", line 103, in setup
    return _setup(**kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/sandhaus/Downloads/yubioath-desktop-yubioath-desktop-2.3.0/yubioath/yubicommon/setup/exe.py", line 76, in run
    pyinst_run([spec_name])
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 63, in <module>
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 441, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'yubioath-desktop' distribution was not found and is required by the application
´´´

**Comment by dainnilsson** [comment] 2015-12-11 09:20
It "works for me". Do you need to build a standalone binary of this yourself?

**Comment by dainnilsson** [comment] 2016-01-04 12:36
Closing this as I can't reproduce it.

**Closed by dainnilsson** 2016-01-04 12:36 UTC
