### ISSUE TITLE
MacOS loses credentials after time in Slot Mode

### ISSUE THREAD

**Issue by nicsyubi** [Yubico/yubioath-desktop#225] opened 2017-12-21 17:00 UTC
Authenticator 4.3.2
MacOS High Sierra 10.13.2
Slot mode operation
Credential requires touch

Insert key, touch to generate OTP then leave
After approx 4 mins the Authenticator says "No credentials found"
After a further minute it will generally find the credential again
Cycle then repeats

Only happens in Slot mode + Touch required
Does not seem to happen on Windows

**Comment by dagheyman** [comment] 2018-01-30 11:03
Closing, not able to reproduce this anymore.

**Closed by dagheyman** 2018-01-30 11:03 UTC
Labels: bug
