### ISSUE TITLE
MacOS says "no credentials found" after some time

### ISSUE THREAD

**Issue by chmac** [Yubico/yubioath-desktop#246] opened 2018-01-29 11:35 UTC
Thank you for opening an issue! If this is a bug report, please include the
following information:

- Yubico Authenticator version: 4.3.2+1
- Operating system and version: MacOS 10.12.6 (same issue on High Sierra)
- YubiKey model and version: Yubikey Neo 3.3.0
- Bug description summary: 

I typically reboot my macs infrequently, perhaps once per month. I have 2, a MacBook and an iMac. Both experience the same problem. After some time, the yubico authenticator application stops generating codes. A reboot of the mac fixes the problem. When it's in the broken state, I open Yubico Authenticator, it says "No YubiKey detected", then "Connecting to YubiKey", then finally (after maybe 20 to 30 seconds) "No credentials found".

I'm not sure how to debug the issue. I've tried different USB ports. I see the same behaviour on both macs (one High Sierra, one Sierra) which leads me to think it's not the computers.

Can I somehow get debugging logs out of the authenticator app?

EDIT: Also, when it's in this "broken" state, quitting Yubico Authenticator does not work. The window disappears, but the application never quits. I need to force quit in order to close it.

**Comment by emlun** [comment] 2018-01-29 11:49
This sounds like a duplicate of #176, are you seeing the same symptoms as described there?

**Comment by chmac** [comment] 2018-01-29 11:52
@emlun I had a look for existing duplicates, but didn't see that one. I don't think it's the same symptoms though, as I read #176 the issue is resolved by restarting the application. In my case, the issue is only resolved by an entire system reboot.

**Comment by dagheyman** [comment] 2018-01-30 08:30
> Can I somehow get debugging logs out of the authenticator app?

You can, just run the app from terminal with the --log-level flag set to DEBUG.
`$ /Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop --log-level DEBUG`

You may also try the current build from master (not signed, no installer), to see if any changes we made since 4.3.2 affects your issue. That build may be found here: https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/yubioath-desktop-master.app.tar

**Comment by chmac** [comment] 2018-01-30 11:08
@dagheyman Thanks for the `--log-level` flag. I tried `--help` but got nothing, and couldn't find any flags in the README. Is there docs anywhere on flags? Open to a PR adding them to the README?

With the `--log-level DEBUG` option the app says "Connecting to YubiKey..." for a much longer time. I aded a timestamp to the start of the logs to record how long it takes.

```
date; /Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop --log-level DEBUG                                chm@cano
Tue 30 Jan 2018 11:52:06 CET
Got library name:  "/Applications/Yubico Authenticator.app/Contents/PlugIns/quick/libpyothersideplugin.dylib"
2018-01-30T11:53:13+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2018-01-30T11:53:13+0100 DEBUG [ykman.descriptor.open_driver:141] Opening driver for serial: None, pid: PID.NEO_OTP_U2F_CCID
2018-01-30T11:53:13+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 1 of 3
2018-01-30T11:53:13+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x111df7400> serial: 3016649, pid: PID.NEO_OTP_U2F_CCID
2018-01-30T12:04:13+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2018-01-30T12:04:13+0100 DEBUG [ykman.descriptor.open_driver:141] Opening driver for serial: 3016649, pid: PID.NEO_OTP_U2F_CCID
2018-01-30T12:04:13+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 1 of 3
2018-01-30T12:04:14+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x111f9e518> serial: 3016649, pid: PID.NEO_OTP_U2F_CCID
```

After leaving it run for a few minutes, I press <kbd>cmd</kbd>+<kbd>q</kbd> inside the app, it closes the window, then goes into the "Not responding" state according to Activity Monitor. If I force-quit, nothing else gets logged to the console except that the process was terminated.

Do the logs above shed any light on the issue?

**Comment by dagheyman** [comment] 2018-01-30 12:11
We'll look into documenting the `log-level` flag, it was added recently and is currently the only flag.

> Do the logs above shed any light on the issue?

Those logs unfortunately dosen't say much more than that the device was eventually opened. Could you try with the build from master that I linked?

**Comment by emlun** [comment] 2018-01-30 12:32
It's currently "documented" only in [NEWS](https://github.com/Yubico/yubioath-desktop/blob/master/NEWS#L25), so I'm not surprised it's not easily discoverable... :)

**Comment by chmac** [comment] 2018-01-30 14:58
@dagheyman I tried the build you linked to by untarring it into `/Applications/` then running it from the console with the `--log-level DEBUG` flag. Same behaviour as the previous version, same crash on quit, but it produces some extra logs.

```
 date; /Applications/yubioath-desktop.app/Contents/MacOS/yubioath-desktop --log-level DEBUG                                     chm@cano
Tue 30 Jan 2018 15:55:24 CET
2018-01-30T15:56:25+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2018-01-30T15:56:25+0100 DEBUG [ykman.descriptor.open_driver:141] Opening driver for serial: None, pid: PID.NEO_OTP_U2F_CCID
2018-01-30T15:56:25+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 1 of 10
2018-01-30T15:56:25+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x10fb1e7f0> serial: 3016649, pid: PID.NEO_OTP_U2F_CCID
2018-01-30T15:56:25+0100 ERROR [ykman.driver_ccid.probe_capabilities_support:142] Failed to probe for capability support. aid: b'\xa0\x00\x00\x06G/\x00\x01', code: CAPABILITY.U2F
Traceback (most recent call last):
  File "/Applications/yubioath-desktop.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_ccid.py", line 137, in probe_capabilities_support
    self.send_apdu(0, INS_SELECT, 4, 0, aid)
  File "/Applications/yubioath-desktop.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_ccid.py", line 159, in send_apdu
    raise APDUError(resp, sw)
ykman.driver_ccid.APDUError: APDU error: SW=0x6d00
```

Does that shed any further light on the issue?

**Comment by dagheyman** [comment] 2018-01-30 15:17
Thank you! So it looks like the ykman library crashes when trying to probe capabilities on your device, will look into why that happens and try to handle it better.

**Comment by dagheyman** [comment] 2018-01-31 12:26
Actually there is some smart card related problems to the firmware version you have (3.3.0) where the card sometimes would auto-eject. I wonder if this could be related to your problem. Could you try switching the connection modes to CCID only, using YubiKey Manager ([GUI](https://github.com/Yubico/yubikey-manager-qt) or [CLI](https://github.com/Yubico/yubikey-manager)),  and see if the behaviour is different?

**Comment by chmac** [comment] 2018-01-31 18:37
@dagheyman I tried the GUI, but when I click the "Confirm" button, nothing happens. The window does not go away. The GUI app also takes forever to load, seems like it's as slow as the Yubico Authenticator app when things are "broken". The GUI also has the same crash-on-quit issue. Anyway, I figured out the command line (docs could be better, no explanation of the options for each command in the docs), and I set the mode to only CCID.

```
./ykman mode
Got library name:  "/Applications/YubiKey Manager.app/Contents/PlugIns/quick/libpyothersideplugin.dylib"
Current connection mode is: CCID
Supported connections are: OTP, U2F, CCID
```

No change. Yubico Authenticator still says "No credentials found", still crashes on quit. I'm back to running the release version, 4.3.2+1 rather than the bleeding edge version.

**Comment by dagheyman** [comment] 2018-02-01 07:55
Thanks for all the debugging help. I'm guessing it's not possible for you to try with another yubikey? At this point, since there are some known issues with CCID on your firmware version, I would suggest [opening a support ticket](https://www.yubico.com/support/get-support/) and looking in to having your device replaced (link them this thread in the ticket).

**Comment by chmac** [comment] 2018-02-01 09:09
@dagheyman I have other yubikeys, but they’re older, don’t know if they support all this smart new stuff. I think I have two of [these](https://technicallyeasy.net/yubikey-the-key-to-online-security/) but I’m not 100% sure. I’ll reach out to support as you suggested also.

**Comment by chmac** [comment] 2018-02-06 18:11
Testing with a brand new yubikey neo, and I have the same very, very long time until it says "No credentials found". There are no credentials on this one, but it takes more than 1 minute to figure that out.

Now I've added one credential, and I have the exact same process as originally reported.

**Comment by dagheyman** [comment] 2018-02-07 08:06
> but it takes more than 1 minute to figure that out

Very wierd, and we can't reproduce this on our macs. Do you have any other software running related to USB or smart cards that you think might be interfering? And just to double check, you see the same behaviour on two different machines?

**Comment by chmac** [comment] 2018-02-07 15:01
Yes, same problem on 2 macs. I do have the Estonian e-residency smartcard stuff installed on my desktop, but I don't think I have that installed on my laptop.

I also have many different yubico apps installed, the authenticator, manager, and personalisation tool. I noticed the request for root permissions during install and I wonder if something has been left over from a previous installation that somehow didn't get properly removed. I'm mostly guessing, have no idea how these things work.

I'll double check if I have the Estonian stuff on the laptop.

**Comment by chmac** [comment] 2018-02-07 22:16
Just checked and definitely I don't have the Estonian e-id smart card apps on my laptop, and I see the same behaviour on the laptop as on the desktop. They're running different versions of MacOS also. I have the yubico authenticator and the yubikey personalisation tool both installed on the laptop.

**Comment by chmac** [comment] 2018-02-13 12:40
@dagheyman I've been testing a bit on my laptop, and I haven't seen the same issue. So it might be that there's a clash between the estonian e-id smart card software and yubico. Any idea how we can debug?

**Comment by dagheyman** [comment] 2018-02-16 08:07
I don't know much about the estonian e-id software. Is it software that is always running? Can I try to reproduce it myself or do I need a e-residency? Does uninstalling it resolve the issue?

There is a new version out of Yubico Authenticator (4.3.3), you could try running that with `--log-level DEBUG` again and see if it spits out anything interesting.

**Comment by chmac** [comment] 2018-02-18 09:03
@dagheyman I'm not sure about the always running question. Is the yubico authenticator always running? I noticed that both require sudo to install, but why that is, I've no idea.

I believe the e-id software can be installed without the need for an id card here: https://installer.id.ee/?lang=eng

**Comment by dagheyman** [comment] 2018-05-08 07:52
Do you have the same issue with 4.3.4 ? Debug logs would be interesting.

**Comment by chmac** [comment] 2018-06-12 09:03
@dagheyman I've been keeping an eye on this. I haven't seen the issue recently. I'll keep an eye on it for another month or so, and if it doesn't reappear in that time, I'll close this issue.

**Comment by dagheyman** [comment] 2018-06-12 09:04
> I've been keeping an eye on this. I haven't seen the issue recently. I'll keep an eye on it for another month or so, and if it doesn't reappear in that time, I'll close this issue.

Sounds good, thanks.

**Comment by BlaineBradbury** [comment] 2018-07-29 22:56
Using 4.3.4 on OSX 10.11.6
Authenticator says "No credentials found."
File > New Credential... Save -- does nothing

**Comment by BlaineBradbury** [comment] 2018-07-29 23:15
2018-07-29T19:12:49-0400 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 0.7.0
2018-07-29T19:12:49-0400 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x1, self.mode.transports: 0x7
2018-07-29T19:12:49-0400 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:12:49-0400 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2018-07-29T19:12:49-0400 DEBUG [ykman.driver_otp.open_devices:180] Success in opening key at position 0
2018-07-29T19:12:49-0400 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_otp.OTPDriver object at 0x1179b15f8>, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:12:49-0400 DEBUG [ykman.device.__init__:196] Read config from device...
2018-07-29T19:12:49-0400 DEBUG [ykman.device.__init__:211] Failed to read config from device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/device.py", line 197, in __init__
    config = DeviceConfig(driver.read_config())
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_otp.py", line 133, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError
2018-07-29T19:12:49-0400 DEBUG [ykman.device.__init__:117] Config data empty/missing
2018-07-29T19:12:49-0400 DEBUG [ykman.device.__init__:225] Identified NEO
2018-07-29T19:12:49-0400 DEBUG [ykman.device.__init__:230] CCID not available, guess capabilities
2018-07-29T19:12:49-0400 DEBUG [ykman.driver_otp.__del__:167] Destroy <ykman.driver_otp.OTPDriver object at 0x1179b15f8>
2018-07-29T19:12:49-0400 DEBUG [ykman.driver_otp.close:162] Close <ykman.driver_otp.OTPDriver object at 0x1179b15f8>
2018-07-29T19:12:50-0400 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x1, self.mode.transports: 0x7
2018-07-29T19:12:50-0400 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:12:50-0400 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2018-07-29T19:12:50-0400 DEBUG [ykman.driver_otp.open_devices:180] Success in opening key at position 0
2018-07-29T19:12:50-0400 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_otp.OTPDriver object at 0x119dd8b38>, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:12:50-0400 DEBUG [ykman.device.__init__:196] Read config from device...
2018-07-29T19:12:50-0400 DEBUG [ykman.device.__init__:211] Failed to read config from device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/device.py", line 197, in __init__
    config = DeviceConfig(driver.read_config())
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_otp.py", line 133, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError
2018-07-29T19:12:50-0400 DEBUG [ykman.device.__init__:117] Config data empty/missing
2018-07-29T19:12:50-0400 DEBUG [ykman.device.__init__:225] Identified NEO
2018-07-29T19:12:50-0400 DEBUG [ykman.device.__init__:230] CCID not available, guess capabilities
2018-07-29T19:12:50-0400 DEBUG [ykman.otp.calculate:201] Sending a challenge to the device. Slot 2. Attempt 1. Wait for touch is False.
2018-07-29T19:12:51-0400 DEBUG [ykman.otp.calculate:211] Got ykpers error 4, b'timeout' as expected.
2018-07-29T19:12:51-0400 DEBUG [ykman.driver_otp.close:162] Close <ykman.driver_otp.OTPDriver object at 0x119dd8b38>
2018-07-29T19:12:51-0400 DEBUG [ykman.driver_otp.__del__:167] Destroy <ykman.driver_otp.OTPDriver object at 0x119dd8b38>
2018-07-29T19:13:51-0400 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x1, self.mode.transports: 0x7
2018-07-29T19:13:51-0400 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:13:51-0400 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2018-07-29T19:13:51-0400 DEBUG [ykman.driver_otp.open_devices:180] Success in opening key at position 0
2018-07-29T19:13:51-0400 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_otp.OTPDriver object at 0x119e0d6d8>, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:13:51-0400 DEBUG [ykman.device.__init__:196] Read config from device...
2018-07-29T19:13:51-0400 DEBUG [ykman.device.__init__:211] Failed to read config from device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/device.py", line 197, in __init__
    config = DeviceConfig(driver.read_config())
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_otp.py", line 133, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError
2018-07-29T19:13:51-0400 DEBUG [ykman.device.__init__:117] Config data empty/missing
2018-07-29T19:13:51-0400 DEBUG [ykman.device.__init__:225] Identified NEO
2018-07-29T19:13:51-0400 DEBUG [ykman.device.__init__:230] CCID not available, guess capabilities
2018-07-29T19:13:51-0400 DEBUG [ykman.otp.calculate:201] Sending a challenge to the device. Slot 2. Attempt 1. Wait for touch is False.
2018-07-29T19:13:52-0400 DEBUG [ykman.otp.calculate:211] Got ykpers error 4, b'timeout' as expected.
2018-07-29T19:13:52-0400 DEBUG [ykman.driver_otp.close:162] Close <ykman.driver_otp.OTPDriver object at 0x119e0d6d8>
2018-07-29T19:13:52-0400 DEBUG [ykman.driver_otp.__del__:167] Destroy <ykman.driver_otp.OTPDriver object at 0x119e0d6d8>
2018-07-29T19:14:53-0400 DEBUG [ykman.descriptor.Descriptor.open_device:80] transports: 0x1, self.mode.transports: 0x7
2018-07-29T19:14:53-0400 DEBUG [ykman.descriptor.open_device:84] Opening driver for serial: None, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:14:53-0400 DEBUG [ykman.descriptor.open_device:86] Attempt 1 of 10
2018-07-29T19:14:53-0400 DEBUG [ykman.driver_otp.open_devices:180] Success in opening key at position 0
2018-07-29T19:14:53-0400 DEBUG [ykman.descriptor.open_device:89] Found driver: <ykman.driver_otp.OTPDriver object at 0x119e0ddd8>, pid: PID.NEO_OTP_FIDO_CCID
2018-07-29T19:14:53-0400 DEBUG [ykman.device.__init__:196] Read config from device...
2018-07-29T19:14:53-0400 DEBUG [ykman.device.__init__:211] Failed to read config from device
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/device.py", line 197, in __init__
    config = DeviceConfig(driver.read_config())
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_otp.py", line 133, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError
2018-07-29T19:14:53-0400 DEBUG [ykman.device.__init__:117] Config data empty/missing

**Closed** 2018-09-26 08:09 UTC
Labels: bug
