### ISSUE TITLE
Option to close/hide window on copy

### ISSUE THREAD

**Issue by phipolis** [Yubico/yubioath-desktop#305] opened 2018-08-10 17:31 UTC
I love that codes automatically copy to the clipboard, but my next action is always to close the window. It would be so nice if the window minimized back to the tray after copying, getting out of the way after generating a code.

**Comment by emlun** [comment] 2018-08-13 11:16
Hi, thanks for reaching out. This looks like a duplicate of #214, which was closed as a wontfix.

**Closed by emlun** 2018-08-13 11:16 UTC
