### ISSUE TITLE
Only can add 7 credentials

### ISSUE THREAD

**Issue by interbiznw** [Yubico/yubioath-desktop#200] opened 2017-11-01 04:20 UTC
Anyone know why it wont let me add more than 7 credentials? Having issue on windows app and android, it says added but does not show anymore than 7

**Comment by emlun** [comment] 2017-11-01 09:57
I'm not able to reproduce this problem in either of the apps. Which versions of the apps and what YubiKey model are you using?

**Comment by emlun** [comment] 2017-11-08 13:40
Closing this for now, you're welcome to reopen it if you have any more information to add.

**Closed by emlun** 2017-11-08 13:40 UTC
