### ISSUE TITLE
Request feature support for exported transfer QR codes from Google Authenticator

### ISSUE THREAD

**Issue by photographer-mememe** [Yubico/yubioath-desktop#780] opened 2022-02-10 07:08 UTC
- Yubico Authenticator version: 2.2.0
- Operating system and version: Android 12 and Windows 10
- YubiKey model and version: 5 NFC

Exported QR codes from Google Authenticator for transfer to other Apps/devices are not the standard OATH format, so Yubico Authenticator is unable to read them.

There are other apps that can read them. It would be nice if Yubico Authenticator could do this too.

From the below Github projects:
_The export QR code of "Google Authenticator" contains the URL "otpauth-migration://offline?data=...".
The data parameter is a base64 encoded proto3 message (Google Protocol Buffers)._

https://github.com/scito/extract_otp_secret_keys

https://github.com/beemdevelopment/Aegis/pull/406

https://developers.google.com/protocol-buffers/docs/pythontutorial

Edit:
Similar to the request in yubioath-android:
https://github.com/Yubico/yubioath-android/issues/128

**Comment by emlun** [comment] 2022-02-10 16:32
Hi! This looks like a duplicate of #675, is it?

**Closed** 2022-02-11 06:59 UTC
