### ISSUE TITLE
Yubico Authenticator opens outside monitors and can not be accessed

### ISSUE THREAD

**Issue by legacycode** [Yubico/yubioath-desktop#241] opened 2018-01-23 16:38 UTC
Thank you for opening an issue! If this is a bug report, please include the
following information:

- Yubico Authenticator version: 4.3.2
- Operating system and version: Windows 10 pro
- YubiKey model and version: Neo
- Bug description summary: 

Yubico Authenticator opens outside monitors and can not be accessed anymore.

Steps to reproduce
---

I am using two 4k monitors with a resolution of 3840x2160 each, where 2 is my main monitor.

![monitors](https://user-images.githubusercontent.com/668759/35287103-e9645912-0061-11e8-8024-abd41d368fe2.JPG)

When opening Authenticator for the first time it is centered on my main monitor 2. I can move the Authenticator on monitor 2 and close it. Evereything works as expected and the settings are store in the registry as follows:

![settings1](https://user-images.githubusercontent.com/668759/35287385-85f6e6dc-0062-11e8-8bce-a5f705cc3703.JPG)

**Problem: When i move the Authenticator to my monitor 1 and i close the Authentcator on monitor 1 i am not able to see it anymore. I can see Authenticator starting and that it seems to be left outside of monitor 1.** Following settings are stored in the windows registry:

![settings2](https://user-images.githubusercontent.com/668759/35287664-2d8535c0-0063-11e8-9f50-c4c96dadca5e.JPG)

Expected result
---

I expect that Authenticator to open at monitor 1 (on same location where i closed it) next time i start the application.

Actual results
---

Authenticator opens outside left montior 1. I can not see it and can not use it. I need to manually delete the registry settings in my windows registry.

Other info
---

Great work and a great tool so far :-) Hopefully this description can help solving this issue. I can test your fix, if there will be one.

**Comment by emlun** [comment] 2018-01-24 12:49
Thanks a lot for the detailed report! I managed to reproduce the behaviour; we should be able to get this fixed.

**Comment by emlun** [comment] 2018-01-24 14:33
This actually seems to already be fixed on master since b183182eccffde7895dff5cc2f0866758554946b, so I'll close this issue. Please let us know if you still have these problems after upgrading to the next release.

**Comment by xetolosch91** [comment] 2020-01-29 09:51
Hi
I seem to have the same problem.

OS: Windows 10 Pro
Yubico Authenticator Version: 5.0.1
Yubikey Modell: 5C

The behaviour is the exact same as described above. So Apparently, this is not fixed? Or is it just a bug in the new version of Yubico Authenticator?

**Comment by legacycode** [comment] 2020-01-29 14:44
@emlun i can confirm that this problem is back. i actually have the same issue.

![image](https://user-images.githubusercontent.com/668759/73366114-aef09800-42ad-11ea-87f6-fab9f89cd745.png)

@xetolosch91 you can reset the yubico authenticator location by setting x and y with regedit to 0. You can find the key at: Computer\HKEY_USERS\[YOUR SID]\SOFTWARE\Yubico\Yubico Authenticator

**Comment by fdennis** [comment] 2020-02-10 08:00
Hey,
Thanks for letting us know about this issue.
Do you have the same scaling setting on both monitors? For example, are they both on 100%? Or is one on 150%, for example?

**Comment by legacycode** [comment] 2020-02-11 07:13
@fdennis Both of my montitors are runnig at 200%.

**Comment by fdennis** [comment] 2020-02-11 07:41
@legacycode Thanks! Seems like scaling is causing the issue. We will look into this once again.

**Comment by fdennis** [comment] 2020-02-11 08:06
@legacycode @xetolosch91 Could you please check if you get the same issue with the latest release, 5.0.2?

**Comment by legacycode** [comment] 2020-02-11 15:42
@fdennis i can reproduce this error with the 5.0.2.

**Closed** 2020-02-18 10:54 UTC
Labels: bug

**Comment by marvinej** [comment] 2020-11-07 15:31
having this issue now on windows 10

**Comment by fdennis** [comment] 2020-11-10 08:18
@marvinej Can you share more details? Does this always happen? How many monitors do you have? Can you solve it?

**Comment by marvinej** [comment] 2020-11-15 03:16
I have 3 monitors 2 4k and a single 1080p

yes, it always happens.

The only workaround I have is to shift right click and select maximize
every time I open the program.
------
Respectfully,
Eli Marvin

**Comment by fdennis** [comment] 2020-11-16 07:44
@marvinej Can you describe what exactly is happening? What OS are you running?

**Comment by mkaczmarek-evenica** [comment] 2026-08-18 17:35
This is still an issue. Happened to me today.
