### ISSUE TITLE
Displays "No credentials found" briefly before showing the credentials list

### ISSUE THREAD

**Issue by cdelg** [Yubico/yubioath-desktop#283] opened 2018-04-16 11:11 UTC
- Yubico Authenticator version: 4.1.3
- Operating system and version: Fedora 27
- YubiKey model and version: Neo
- Bug description summary: The authenticator displays "No credentials found" briefly before showing the credentials list when the app instance reads the Yubikey for the first time.

Steps to reproduce
---

* The Yubikey must contain at least one credential.
* Launch the authenticator and plug the Yubikey OR plug the Yubikey and start the authenticator app.

Expected result
---

The authenticator app must display "Reading credentials..." and then the list of credentials.

Actual results
---

The authenticator app displays "No credentials found" briefly before showing the credentials list.

Other info
---

If you remove and reinsert the Yubikey and keep the authenticator app open the problem disappears.

**Comment by dagheyman** [comment] 2018-04-18 07:01
Thanks for the report! Since I cant reproduce this in the latest version (4.3.3) on Ubuntu, I'm closing this though.

**Comment by cdelg** [comment] 2018-04-20 07:50
The problem is also in 4.3.3 on Windows

**Closed** 2018-04-25 11:35 UTC
Labels: bug
