### ISSUE TITLE
yubioath-desktop is gone after applying updates, can't be reinstalled

### ISSUE THREAD

**Issue by ilya40umov** [Yubico/yubioath-desktop#261] opened 2018-02-09 19:49 UTC
OS: Linux Mint 18.3

After having applied updates from Update Manager, yubioath-desktop was gone form the system on the following boot. I've removed all yubico-related packages from the system, removed the ppa run the following steps:

```
$ sudo apt-add-repository ppa:yubico/stable
$ sudo apt update
$ sudo apt install yubioath-desktop
```

I'm consistently getting the following error:

```
The following packages have unmet dependencies:
 yubioath-desktop : Depends: python3-yubikey-manager (>= 0.5.0) but it is not installable
                    Depends: python3-yubikey-manager (<= 0.6) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Where can find this dependency? (python3-yubikey-manager)

**Comment by ilya40umov** [comment] 2018-02-09 21:43
In attempt to work around the issue I was able to install `yubioath-desktop` with pip,
which I can now run with `python3 -m yubioath.gui`. However, it's version 3.1.0, so I would prefer to be able to install the latest version still.

**Comment by ilya40umov** [comment] 2018-02-09 21:48
And I was actually able to install `yubikey-manager (0.6.0)` with pip which I assume is the same dependency as `python3-yubikey-manager` that `apt-get` was not able to find.

**Comment by emlun** [comment] 2018-02-09 23:26
Thanks for the report, this is a duplicate of #260. This is a mistake on our part - we released a new yubikey-manager, but haven't yet done a new yubioath-desktop release that upgrades its dependency. We didn't expect package managers to silently remove incompatible packages on upgrade instead of holding the current versions of non-upgradable packages...

We've requested de-publication of the new yubikey-manager, so version 0.5 should soon again be the latest version available. Please let us know if this isn't resolved by the beginning of next week.

**Comment by ilya40umov** [comment] 2018-02-10 17:39
@emlun Thanks for the update. I would personally leave this issue open until it's actually solved (or you could leave #260 open instead, it makes no difference). Just to make sure people won't keep creating bug reports of the same problem.
Anyways, I'll let you know if this problem does not go away during the next week.

**Comment by emlun** [comment] 2018-02-10 18:50
Good point, thanks!

**Comment by ilya40umov** [comment] 2018-02-12 12:48
Today I have successfully re-installed `yubioath-desktop` from the repo. Thanks a lot again for the fast responses!
@emlun Unrelated question: should I also be able to install the latest version of `python3-yubikey-manager` with pip or this option is no longer supported? (Mostly just curious)

**Comment by dagheyman** [comment] 2018-02-12 14:42
Glad that it's working again. Closing this issue then.

> Unrelated question: should I also be able to install the latest version of python3-yubikey-manager with pip or this option is no longer supported? (Mostly just curious)

The version of python3-yubikey-manager found in the Ubuntu PPA will stay on 0.5.0 for now, while the version found in pip is 0.6.0. Both should be compatible with current version of Yubico Authenticator. I recommend just relying on the one found in the PPA, since it will be updated automatically together with your other software.

**Closed by dagheyman** 2018-02-12 14:42 UTC

**Comment by Trebor87** [comment] 2024-02-21 14:41
This seem related to the above problems

Arch Linux as of today 21/02/24

 yubioath-flutter git repo ... %s is unable to verify the signature.
git
==> ERROR: One or more PGP signatures could not be verified!
 -> error making: yubico-authenticator-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
yubico-authenticator - exit status 1
