### ISSUE TITLE
Percent-encoded space in credential name

### ISSUE THREAD

**Issue by doherty** [Yubico/yubioath-desktop#50] opened 2015-08-30 22:45 UTC
After scanning a QR code (btw, that's a kick-ass feature `<3`), I have an entry called `Slack%20(Hashbang):mike@mikedoherty.ca` which should've been percent-decoded. Unfortunately, I don't see any way to edit it as a workaround.

**Comment by dainnilsson** [comment] 2015-08-31 08:18
This is a duplicate of #44. It's been fixed, but has not been published in a release yet. You should be able to edit the field after scanning the code, but before saving it to the device to manually fix the label. Once the credential has been saved to the device you'll have to delete it and re-add it to modify it I'm afraid.

P.S. I'm glad you appreciate the effort I put into writing a QR decoder from scratch ;)

**Closed by dainnilsson** 2015-08-31 08:18 UTC
