### ISSUE TITLE
HiDPI support: scaling factor 1.5 under gnome

### ISSUE THREAD

**Issue by jonasfj** [Yubico/yubioath-desktop#203] opened 2017-11-14 19:19 UTC
Basically, this is horribly broken on HiDPI displays.

The pre-QML UI worked perfectly fine under gnome. I'm sticking with 2.3.0 for now.

Please provide a functioning UI or at-least add a CLI option with json output so we make something that works. This is arguably a critical feature.

**Comment by emlun** [comment] 2017-11-15 09:53
Thank you for the report, but please provide more details about what is broken and how. I'm currently running this on a down-scaled HiDPI display in i3wm with no problems. These are my screen layout settings:

```
xrandr \
  --output eDP1 --mode 3200x1800 --scale 0.5x0.5 --pos 0x540 --rotate normal \
  --output DP1 --primary --mode 2560x1440 --pos 1600x0 --rotate normal
```

**Comment by jonasfj** [comment] 2017-11-15 22:24
I'm on gnome-shell under Ubuntu 16.04, with scaling-factor 1.7 in gnome-tweak tools; I'll admit I didn't look into what it did after that.

I suspect the issue is that the QML UI doesn't assimilate to the desktop environment. Normal qt-widget applications will use GUI style gtk or something.

I'll admit I'm not up to speed with how it does the scaling-factor magic, or how QML does it's magic... barely even how the old qt-widget style apps get gtk theming.

The more I think about it, the only easy way to solve this is:
 1) Tweak the QML app to use qt-widgets and native theming the way qt4 widgets do...
 2) Try a newer version of gnome that might have better scaling support (or wait for this to get fixed at gnome level)

I guess one could argue this is a tweaking issue in my desktop setup, wrt. to qt5/qml... I'm not sure.

**Comment by emlun** [comment] 2017-11-17 15:01
What exactly is the issue you're seeing?

 1. What is your expectation?
 2. What is the actual result?

It looks fine to me:

x1 scale:
![scale1](https://user-images.githubusercontent.com/1367758/32953385-50ef817e-cbb0-11e7-8a9b-70a327c9ccd1.png)

x2 scale:
![scale2](https://user-images.githubusercontent.com/1367758/32953386-511eb494-cbb0-11e7-82e7-de39bb52b787.png)

**Comment by emlun** [comment] 2017-11-17 15:29
Closing this until more details come in, just to get it out of the "inbox". Please reopen it when you respond!

**Closed by emlun** 2017-11-17 15:29 UTC

**Comment by emlun** [comment] 2017-12-07 13:51
Another user had a similar issue with scaling, in which case it turned out to be caused by the monitor reporting bad EDID information. Does https://github.com/Yubico/yubioath-desktop/issues/213#issuecomment-349872743 help in your case?

**Comment by jonasfj** [comment] 2017-12-08 01:13
So my desktop is not a 1X or 2X scale, which probably what causes this... It's a 1.5x or something like that. Result being that it's scaled because the desktop environment scales the font size in all apps.

Most gtk apps are good detecting this. Most qt apps too, but some commercially package qt apps like dropbox are useless :)

I built locally, side note you might want to update [build instructions](https://developers.yubico.com/yubioath-desktop/Building_from_Source.html) to say `qmake -qt=qt5 && make`. I have ykman installed, so I'm not sure why it complains (see terminal), but that's probably a packaging thing, that part seems to work when installed as debian package.

![screenshot from 2017-12-07 16-30-50](https://user-images.githubusercontent.com/149732/33745513-1a441ace-db6c-11e7-90cf-73c3d566b9e0.png)

Anyways, the scaling issue is obvious.

----
After digging further I think:
 * `QT_SCALE_FACTOR` will be supported on `qt >= 5.4`
 * Qt 5.1 on Ubuntu 16.04 has a bug where it doesn't scale font using system settings from gnome
 * Any suggestions for workaround I could find involved installing something from sketchy PPAs... so I didn't try them...

Maybe the best option is to not upgrade `yubioath-desktop` and deal with this once Ubuntu 18.04 is out.

**Comment by emlun** [comment] 2017-12-08 16:52
That looks very similar to #213. Did you check if the cause, and possibly solution, presented there applies to you too?

The `PyOtherSide error`s are caused by a combination of two things: we've made an unreleased breaking change to the `ykman` Python library, and yubioath-desktop on Linux loads `ykman` from the system Python path. Should you ever need to, you can resolve this as described in the [development doc][devdoc].

[devdoc]: https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc#run-the-app
