### ISSUE TITLE
`pcscd` installation requires root privileges

### ISSUE THREAD

**Issue by UNakade** [Yubico/yubioath-desktop#1377] opened 2024-02-05 17:08 UTC
Is there any way to get TOTPs from the Yubikey if I don't have root privileges and the `pcscd` service is not running (Linux)?

**Comment by dainnilsson** [comment] 2024-02-09 12:34
Not that I'm aware of. Even if you were to write your own PC/SC layer, you would need access to the USB device which you probably couldn't grant without root.

**Comment by UNakade** [comment] 2024-02-10 10:31
Ok, wow. So merely having two factors of authentication (something you know: your password, and something you have: the Yubikey) isn't enough. The Yubikey is essentially useless for TOTPs unless you also have root privileges. Seems like a really big ask. 

I can still use the passkeys stored on my Yubikey through a web browser even if the `pcscd` service is not running. Does Firefox have a different way of communicating with the Yubikey? Could that possibly be leveraged to access the TOTPs?

**Comment by dainnilsson** [comment] 2024-02-10 10:46
You do not need to be running as root yourself to access TOTPs, but the required system configuration must be in place and allow you to access the device, which is no different than other hardware access.

pcscd is a system service that typically runs as root to provide non-root users (assuming they have permissions configured, typically via group membership) access to smartcards. This is analogous to how the udev service runs as root to grant permissions to non-root users for specific devices based on configuration.

While FIDO does not specifically require pcscd, it still requires a service running as root (udev) that is properly configured, just as the TOTP functionality does.

**Comment by UNakade** [comment] 2024-02-10 11:24
Thank you for your response. I guess my problem arises because USB sticks are a lot more popular than security keys and administrators (at, say, a university) are much more likely to enable USB thumb drive access for users than they are to enable smart card access. 
If I do have access to USB devices (like files on a thumb drive or the passkeys in my Yubikey), is there a way to access the TOTPs (through, say, a user installation of the `PCSClite` library)?
For now, my best bet seems to be to store the TOTP secrets in a password manager which I can unlock using a passkey stored on my Yubikey.

**Comment by del-leehopper** [comment] 2024-02-12 11:09
@UNakade sorry for butting into the conversation, but I wanted to suggest that you talk with your University IT Department to resolve your issue. No-doubt others will want to use YubiKey's (or similar Security Keys) in the future, and you might be saving them the hassle if you work with the IT Department to resolve the issue. Whatever their solution would be good to hear back from you so that other organisations can learn from this.

Feel free to ignore me if I got the wrong end of the stick and hope you get your problem resolved.

**Comment by dainnilsson** [comment] 2024-02-12 12:02
I would agree with @del-leehopper on this: Even if you have the required access to the device (which in a University setting is probably less likely than having pcscd installed and running) and it is theoretically possible to then run the missing parts without root, it really seems to be the wrong way to solve the issue. There a very many types of USB devices, and permissions are typically granted (or not) based on type.

**Comment by dainnilsson** [comment] 2024-02-12 12:05
Of course, there's also the option of using Yubico Authenticator on your phone to get TOTPs without having to deal with permissions of the University computers.

**Comment by del-leehopper** [comment] 2024-02-12 12:22
> For now, my best bet seems to be to store the TOTP secrets in a password manager which I can unlock using a passkey stored on my Yubikey.

I would agree with @dainnilsson, using your person mobile while they 'fix' the issue is much better from a security standpoint (assuming that is important to you). The main difference being that TOTP's stored in a Password Manager can still be stolen through many methods as the 'Secret' is quite easy to retreive (unless you are re-authenticating every time you try to access - and even then, the Secret will normally be decrypted to plain text to enable a TOTP to be generated, and then deleted again).

Conversely, once that Secret is stored on the YubiKey, you can never retrieve it (unless you took a copy of it/the QR code before scanning) - hence your overall security is increased. (You still have the issue of that secret being stored on the public server for them to do the TOTP calculation too, but that's why FIDO is preferred).

Either way, it would be interesting to find out if the University solve your issue and what they did to fix it.

**Comment by dainnilsson** [comment] 2024-02-26 13:38
Closing this now, hopefully you found a workaround to the situation.

**Closed as completed by dainnilsson** 2024-02-26 13:38 UTC
