### ISSUE TITLE
Yubikey shows no accounts PermissionError: [Errno 13] Permission denied: '/dev/hidraw2' ykman.hid.linux.list_devices:108] Failed opening HID device

### ISSUE THREAD

**Issue by youidzero** [Yubico/yubioath-desktop#767] opened 2021-12-22 02:27 UTC
- Yubico Authenticator version: Yubico Authenticator        com.yubico.yubioath                                   5.1.0                 stable      system
- Operating system and version: Fedora release 35 (Thirty Five) 5.15.10-200.fc35.x86_64
- YubiKey model and version: Yubikey 5Ci Firmware: 5.2.7
- Yubikey model and version 2: Yubikey 5C Firmware 5.2.6
- Bug description summary: Yubikey shows no accounts 

Steps to reproduce
$ flatpak run com.yubico.yubioath --log-level DEBUG

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]
I ran the flatpak command with DEBUG mode enabled this is the expected result. 

Expected result
I expected to see my yubikey with account info

[What did you expect to happen when you did the above?]

Actual results

flatpak run com.yubico.yubioath --log-level DEBUG
QSocketNotifier: Can only be used with threads started with QThread
Got library name:  "/app/lib/qml/io/thp/pyotherside/libpyothersideplugin.so"
2021-12-21T21:14:57-0500 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2021-12-21T21:14:57-0500 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.7
2021-12-21T21:14:57-0500 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.9.9 (main, Nov 10 2011, 15:00:00) 
[GCC 11.2.0]
2021-12-21T21:14:57-0500 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: linux
2021-12-21T21:14:57-0500 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: x86_64
2021-12-21T21:14:57-0500 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: False
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw7'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw6'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw5'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw4'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw2'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw1'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw0'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw3'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw7'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw6'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw5'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw4'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw2'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw1'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw0'
2021-12-21T21:14:57-0500 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 13] Permission denied: '/dev/hidraw3'
2021-12-21T21:14:57-0500 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw7

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by fdennis** [comment] 2021-12-22 06:35
Closing since this is a duplicate of https://github.com/Yubico/yubioath-desktop/issues/750 . Please check my comment in that thread https://github.com/Yubico/yubioath-desktop/issues/750#issuecomment-996681092

**Closed by fdennis** 2021-12-22 06:35 UTC
