### ISSUE TITLE
On OSX overtime you run yubioath it succeeds but prints error message "Failed to execute script yubioath-script"

### ISSUE THREAD

**Issue by zephyia** [Yubico/yubioath-desktop#88] opened 2016-08-04 02:08 UTC
Using version 3.0.1 installed using the OS X package, when you run the yuioath cli client (any command) the command itself works but it always displays the error message 'Failed to execute script yubioath-script'

**Comment by dagheyman** [comment] 2016-08-09 12:19
Possibly related to [this](https://github.com/pyinstaller/pyinstaller/issues/1978), will look into it.

**Comment by dagheyman** [comment] 2016-08-09 12:52
Yes [building the bootloader](http://pyinstaller.readthedocs.io/en/latest/bootloader-building.html) manually for PyInstaller as suggested seems to resolve this issue. Will do this (if the issue is not fixed in PyInstaller) for the next release.

**Closed** 2016-08-09 12:54 UTC
